//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN()
        {
            this.HOA_DON_BAN_HANG = new HashSet<HOA_DON_BAN_HANG>();
        }
    
        public int Ma_Ban { get; set; }
        public string Ten_Ban { get; set; }
        public Nullable<int> Ma_Khu_Vuc { get; set; }
        public Nullable<bool> Tinh_Trang { get; set; }
        public Nullable<int> Ma_Ban_Chuyen_Den { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_BAN_HANG> HOA_DON_BAN_HANG { get; set; }
        public virtual KHU_VUC KHU_VUC { get; set; }
    }
}
