//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON_BAN_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON_BAN_HANG()
        {
            this.CHI_TIET_HD_BAN_HANG = new HashSet<CHI_TIET_HD_BAN_HANG>();
        }
    
        public int Ma_Hoa_Don { get; set; }
        public string Ma_Nhan_Vien { get; set; }
        public int Ma_Ban { get; set; }
        public Nullable<int> Ma_Khach_Hang { get; set; }
        public System.DateTime Date_HDBH { get; set; }
        public int Tong_Tien { get; set; }
        public Nullable<int> Diem_Tich_Luy { get; set; }
        public Nullable<int> Giam_Gia { get; set; }
    
        public virtual BAN BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_HD_BAN_HANG> CHI_TIET_HD_BAN_HANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
