//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.HOA_DON_BAN_HANG = new HashSet<HOA_DON_BAN_HANG>();
        }
    
        public int Ma_Khach_Hang { get; set; }
        public int Ma_Loai_Khach_Hang { get; set; }
        public string Ten_Khach_Hang { get; set; }
        public string Dia_Chi { get; set; }
        public string SDT { get; set; }
        public int Diem_Tich_Luy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_BAN_HANG> HOA_DON_BAN_HANG { get; set; }
        public virtual LOAI_KHACH_HANG LOAI_KHACH_HANG { get; set; }
    }
}
