//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_V3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PBL_VS1Entities : DbContext
    {
        public PBL_VS1Entities()
            : base("name=PBL_VS1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN> BANs { get; set; }
        public virtual DbSet<CHI_TIET_HD_BAN_HANG> CHI_TIET_HD_BAN_HANG { get; set; }
        public virtual DbSet<HANG_HOA> HANG_HOA { get; set; }
        public virtual DbSet<HOA_DON_BAN_HANG> HOA_DON_BAN_HANG { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHU_VUC> KHU_VUC { get; set; }
        public virtual DbSet<LOAI_HANG_HOA> LOAI_HANG_HOA { get; set; }
        public virtual DbSet<LOAI_KHACH_HANG> LOAI_KHACH_HANG { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
    }
}
