//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAN_VIEN()
        {
            this.HOA_DON_BAN_HANG = new HashSet<HOA_DON_BAN_HANG>();
        }
    
        public string Ma_Nhan_Vien { get; set; }
        public string Ten_Nhan_Vien { get; set; }
        public string Gioi_Tinh { get; set; }
        public string Chuc_Vu { get; set; }
        public bool Phan_Quyen { get; set; }
        public string Dia_Chi { get; set; }
        public string SDT { get; set; }
        public string Mat_Khau { get; set; }
        public int Tinh_Trang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON_BAN_HANG> HOA_DON_BAN_HANG { get; set; }
    }
}
